---

- name: Install prometheus_extra_packages
  openbsd_pkg:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ prometheus_extra_packages }}"

- name: Enable prometheus and set flags for prometheus
  service:
    name: "{{ prometheus_service }}"
    enabled: yes
    arguments: "{{ prometheus_flags }}"
  notify:
    - Restart prometheus

- name: Install prometheus
  openbsd_pkg:
    name: "{{ prometheus_package }}"
    state: present
